*** Starting uWSGI 2.0.17 (64bit) on [Sat May 12 00:42:19 2018] ***
compiled with version: 6.4.0 20170724 on 11 May 2018 10:53:29
os: Linux-4.9.0-deepin13-amd64 #1 SMP PREEMPT Deepin 4.9.57-1 (2017-10-19)
nodename: chier
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/chier/Desktop/django/shareview
writing pidfile to /home/chier/Desktop/django/shareview/script/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 14928
limiting address space of processes...
your process address space limit is 536870912 bytes (512 MB)
your memory page size is 4096 bytes
detected max file descriptor number: 1024
VirtualHosting mode enabled.
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (127.0.0.1:9090).
bind(): Address already in use [core/socket.c line 769]
*** Starting uWSGI 2.0.17 (64bit) on [Sat May 12 00:44:45 2018] ***
compiled with version: 6.4.0 20170724 on 11 May 2018 10:53:29
os: Linux-4.9.0-deepin13-amd64 #1 SMP PREEMPT Deepin 4.9.57-1 (2017-10-19)
nodename: chier
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/chier/Desktop/django/shareview
writing pidfile to /home/chier/Desktop/django/shareview/script/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 14928
limiting address space of processes...
your process address space limit is 536870912 bytes (512 MB)
your memory page size is 4096 bytes
detected max file descriptor number: 1024
VirtualHosting mode enabled.
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:9091 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 2.7.13+ (default, Jul 19 2017, 18:15:03)  [GCC 6.4.0 20170704]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x5579abfd83b0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218760 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 5592)
spawned uWSGI worker 1 (pid: 5593, cores: 1)
spawned uWSGI worker 2 (pid: 5594, cores: 1)
*** Starting uWSGI 2.0.17 (64bit) on [Sat May 12 00:45:16 2018] ***
compiled with version: 6.4.0 20170724 on 11 May 2018 10:53:29
os: Linux-4.9.0-deepin13-amd64 #1 SMP PREEMPT Deepin 4.9.57-1 (2017-10-19)
nodename: chier
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/chier/Desktop/django/shareview
writing pidfile to /home/chier/Desktop/django/shareview/script/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 14928
limiting address space of processes...
your process address space limit is 536870912 bytes (512 MB)
your memory page size is 4096 bytes
detected max file descriptor number: 1024
VirtualHosting mode enabled.
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (127.0.0.1:9091).
bind(): Address already in use [core/socket.c line 769]
*** Starting uWSGI 2.0.17 (64bit) on [Sat May 12 00:47:20 2018] ***
compiled with version: 6.4.0 20170724 on 11 May 2018 10:53:29
os: Linux-4.9.0-deepin13-amd64 #1 SMP PREEMPT Deepin 4.9.57-1 (2017-10-19)
nodename: chier
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/chier/Desktop/django/shareview
writing pidfile to /home/chier/Desktop/django/shareview/script/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 14928
limiting address space of processes...
your process address space limit is 536870912 bytes (512 MB)
your memory page size is 4096 bytes
detected max file descriptor number: 1024
VirtualHosting mode enabled.
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (127.0.0.1:9091).
bind(): Address already in use [core/socket.c line 769]
*** Starting uWSGI 2.0.17 (64bit) on [Sat May 12 00:48:22 2018] ***
compiled with version: 6.4.0 20170724 on 11 May 2018 10:53:29
os: Linux-4.9.0-deepin13-amd64 #1 SMP PREEMPT Deepin 4.9.57-1 (2017-10-19)
nodename: chier
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/chier/Desktop/django/shareview
writing pidfile to /home/chier/Desktop/django/shareview/script/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 14928
limiting address space of processes...
your process address space limit is 536870912 bytes (512 MB)
your memory page size is 4096 bytes
detected max file descriptor number: 1024
VirtualHosting mode enabled.
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (127.0.0.1:9091).
bind(): Address already in use [core/socket.c line 769]
chdir(): No such file or directory [plugins/python/pyloader.c line 109]
Traceback (most recent call last):
  File "./shareview/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ImportError: No module named django.core.wsgi
unable to load app 0 (mountpoint='127.0.0.1|') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
127.0.0.1 [pid: 5593|app: -1|req: -1/1] 127.0.0.1 () {48 vars in 813 bytes} [Sat May 12 00:48:30 2018] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
chdir(): No such file or directory [plugins/python/pyloader.c line 109]
Traceback (most recent call last):
  File "./shareview/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ImportError: No module named django.core.wsgi
unable to load app 0 (mountpoint='127.0.0.1|') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
127.0.0.1 [pid: 5593|app: -1|req: -1/2] 127.0.0.1 () {50 vars in 809 bytes} [Sat May 12 00:48:30 2018] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
chdir(): No such file or directory [plugins/python/pyloader.c line 109]
Traceback (most recent call last):
  File "./shareview/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ImportError: No module named django.core.wsgi
unable to load app 0 (mountpoint='127.0.0.1|') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
127.0.0.1 [pid: 5593|app: -1|req: -1/3] 127.0.0.1 () {48 vars in 813 bytes} [Sat May 12 00:48:31 2018] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
chdir(): No such file or directory [plugins/python/pyloader.c line 109]
Traceback (most recent call last):
  File "./shareview/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ImportError: No module named django.core.wsgi
unable to load app 0 (mountpoint='127.0.0.1|') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
127.0.0.1 [pid: 5593|app: -1|req: -1/4] 127.0.0.1 () {50 vars in 809 bytes} [Sat May 12 00:48:31 2018] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
chdir(): No such file or directory [plugins/python/pyloader.c line 109]
Traceback (most recent call last):
  File "./shareview/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ImportError: No module named django.core.wsgi
unable to load app 0 (mountpoint='127.0.0.1|') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
127.0.0.1 [pid: 5593|app: -1|req: -1/5] 127.0.0.1 () {48 vars in 813 bytes} [Sat May 12 00:48:31 2018] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
chdir(): No such file or directory [plugins/python/pyloader.c line 109]
Traceback (most recent call last):
  File "./shareview/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ImportError: No module named django.core.wsgi
unable to load app 0 (mountpoint='127.0.0.1|') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
127.0.0.1 [pid: 5593|app: -1|req: -1/6] 127.0.0.1 () {50 vars in 809 bytes} [Sat May 12 00:48:31 2018] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
chdir(): No such file or directory [plugins/python/pyloader.c line 109]
Traceback (most recent call last):
  File "./shareview/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ImportError: No module named django.core.wsgi
unable to load app 0 (mountpoint='127.0.0.1|') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
127.0.0.1 [pid: 5594|app: -1|req: -1/7] 127.0.0.1 () {48 vars in 813 bytes} [Sat May 12 00:48:31 2018] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
chdir(): No such file or directory [plugins/python/pyloader.c line 109]
Traceback (most recent call last):
  File "./shareview/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ImportError: No module named django.core.wsgi
unable to load app 0 (mountpoint='127.0.0.1|') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
127.0.0.1 [pid: 5594|app: -1|req: -1/8] 127.0.0.1 () {50 vars in 809 bytes} [Sat May 12 00:48:32 2018] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
chdir(): No such file or directory [plugins/python/pyloader.c line 109]
Traceback (most recent call last):
  File "./shareview/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ImportError: No module named django.core.wsgi
unable to load app 0 (mountpoint='127.0.0.1|') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
127.0.0.1 [pid: 5594|app: -1|req: -1/9] 127.0.0.1 () {48 vars in 813 bytes} [Sat May 12 00:48:32 2018] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
chdir(): No such file or directory [plugins/python/pyloader.c line 109]
Traceback (most recent call last):
  File "./shareview/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ImportError: No module named django.core.wsgi
unable to load app 0 (mountpoint='127.0.0.1|') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
127.0.0.1 [pid: 5594|app: -1|req: -1/10] 127.0.0.1 () {50 vars in 809 bytes} [Sat May 12 00:48:32 2018] GET /favicon.ico => generated 21 bytes in 1 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
chdir(): No such file or directory [plugins/python/pyloader.c line 109]
Traceback (most recent call last):
  File "./shareview/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ImportError: No module named django.core.wsgi
unable to load app 0 (mountpoint='127.0.0.1|') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
127.0.0.1 [pid: 5594|app: -1|req: -1/11] 127.0.0.1 () {48 vars in 813 bytes} [Sat May 12 00:48:45 2018] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
chdir(): No such file or directory [plugins/python/pyloader.c line 109]
Traceback (most recent call last):
  File "./shareview/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ImportError: No module named django.core.wsgi
unable to load app 0 (mountpoint='127.0.0.1|') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
127.0.0.1 [pid: 5593|app: -1|req: -1/12] 127.0.0.1 () {50 vars in 809 bytes} [Sat May 12 00:48:45 2018] GET /favicon.ico => generated 21 bytes in 1 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
chdir(): No such file or directory [plugins/python/pyloader.c line 109]
Traceback (most recent call last):
  File "./shareview/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ImportError: No module named django.core.wsgi
unable to load app 0 (mountpoint='127.0.0.1|') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
127.0.0.1 [pid: 5593|app: -1|req: -1/13] 127.0.0.1 () {48 vars in 813 bytes} [Sat May 12 00:48:46 2018] GET / => generated 21 bytes in 1 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
chdir(): No such file or directory [plugins/python/pyloader.c line 109]
Traceback (most recent call last):
  File "./shareview/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ImportError: No module named django.core.wsgi
unable to load app 0 (mountpoint='127.0.0.1|') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
127.0.0.1 [pid: 5593|app: -1|req: -1/14] 127.0.0.1 () {50 vars in 809 bytes} [Sat May 12 00:48:46 2018] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
chdir(): No such file or directory [plugins/python/pyloader.c line 109]
Traceback (most recent call last):
  File "./shareview/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ImportError: No module named django.core.wsgi
unable to load app 0 (mountpoint='127.0.0.1|') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
127.0.0.1 [pid: 5593|app: -1|req: -1/15] 127.0.0.1 () {48 vars in 813 bytes} [Sat May 12 00:48:46 2018] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
chdir(): No such file or directory [plugins/python/pyloader.c line 109]
Traceback (most recent call last):
  File "./shareview/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ImportError: No module named django.core.wsgi
unable to load app 0 (mountpoint='127.0.0.1|') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
127.0.0.1 [pid: 5594|app: -1|req: -1/16] 127.0.0.1 () {50 vars in 809 bytes} [Sat May 12 00:48:46 2018] GET /favicon.ico => generated 21 bytes in 1 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
chdir(): No such file or directory [plugins/python/pyloader.c line 109]
Traceback (most recent call last):
  File "./shareview/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ImportError: No module named django.core.wsgi
unable to load app 0 (mountpoint='127.0.0.1|') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
127.0.0.1 [pid: 5593|app: -1|req: -1/17] 127.0.0.1 () {48 vars in 813 bytes} [Sat May 12 00:48:46 2018] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
chdir(): No such file or directory [plugins/python/pyloader.c line 109]
Traceback (most recent call last):
  File "./shareview/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ImportError: No module named django.core.wsgi
unable to load app 0 (mountpoint='127.0.0.1|') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
127.0.0.1 [pid: 5594|app: -1|req: -1/18] 127.0.0.1 () {50 vars in 809 bytes} [Sat May 12 00:48:46 2018] GET /favicon.ico => generated 21 bytes in 1 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
chdir(): No such file or directory [plugins/python/pyloader.c line 109]
Traceback (most recent call last):
  File "./shareview/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ImportError: No module named django.core.wsgi
unable to load app 0 (mountpoint='127.0.0.1|') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
127.0.0.1 [pid: 5593|app: -1|req: -1/19] 127.0.0.1 () {48 vars in 813 bytes} [Sat May 12 00:48:46 2018] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
chdir(): No such file or directory [plugins/python/pyloader.c line 109]
Traceback (most recent call last):
  File "./shareview/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ImportError: No module named django.core.wsgi
unable to load app 0 (mountpoint='127.0.0.1|') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
127.0.0.1 [pid: 5593|app: -1|req: -1/20] 127.0.0.1 () {50 vars in 809 bytes} [Sat May 12 00:48:46 2018] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
chdir(): No such file or directory [plugins/python/pyloader.c line 109]
Traceback (most recent call last):
  File "./shareview/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ImportError: No module named django.core.wsgi
unable to load app 0 (mountpoint='127.0.0.1|') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
127.0.0.1 [pid: 5593|app: -1|req: -1/21] 127.0.0.1 () {48 vars in 813 bytes} [Sat May 12 00:48:47 2018] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
chdir(): No such file or directory [plugins/python/pyloader.c line 109]
Traceback (most recent call last):
  File "./shareview/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ImportError: No module named django.core.wsgi
unable to load app 0 (mountpoint='127.0.0.1|') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
127.0.0.1 [pid: 5593|app: -1|req: -1/22] 127.0.0.1 () {50 vars in 809 bytes} [Sat May 12 00:48:47 2018] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
chdir(): No such file or directory [plugins/python/pyloader.c line 109]
Traceback (most recent call last):
  File "./shareview/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ImportError: No module named django.core.wsgi
unable to load app 0 (mountpoint='127.0.0.1|') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
127.0.0.1 [pid: 5594|app: -1|req: -1/23] 127.0.0.1 () {48 vars in 813 bytes} [Sat May 12 00:48:47 2018] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
chdir(): No such file or directory [plugins/python/pyloader.c line 109]
Traceback (most recent call last):
  File "./shareview/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ImportError: No module named django.core.wsgi
unable to load app 0 (mountpoint='127.0.0.1|') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
127.0.0.1 [pid: 5593|app: -1|req: -1/24] 127.0.0.1 () {50 vars in 809 bytes} [Sat May 12 00:48:47 2018] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
chdir(): No such file or directory [plugins/python/pyloader.c line 109]
Traceback (most recent call last):
  File "./shareview/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ImportError: No module named django.core.wsgi
unable to load app 0 (mountpoint='127.0.0.1|') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
127.0.0.1 [pid: 5593|app: -1|req: -1/25] 127.0.0.1 () {48 vars in 813 bytes} [Sat May 12 00:48:47 2018] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
chdir(): No such file or directory [plugins/python/pyloader.c line 109]
Traceback (most recent call last):
  File "./shareview/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ImportError: No module named django.core.wsgi
unable to load app 0 (mountpoint='127.0.0.1|') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
127.0.0.1 [pid: 5593|app: -1|req: -1/26] 127.0.0.1 () {50 vars in 809 bytes} [Sat May 12 00:48:47 2018] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
chdir(): No such file or directory [plugins/python/pyloader.c line 109]
Traceback (most recent call last):
  File "./shareview/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ImportError: No module named django.core.wsgi
unable to load app 0 (mountpoint='127.0.0.1|') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
127.0.0.1 [pid: 5593|app: -1|req: -1/27] 127.0.0.1 () {48 vars in 813 bytes} [Sat May 12 00:48:47 2018] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
chdir(): No such file or directory [plugins/python/pyloader.c line 109]
Traceback (most recent call last):
  File "./shareview/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ImportError: No module named django.core.wsgi
unable to load app 0 (mountpoint='127.0.0.1|') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
127.0.0.1 [pid: 5593|app: -1|req: -1/28] 127.0.0.1 () {50 vars in 809 bytes} [Sat May 12 00:48:47 2018] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
chdir(): No such file or directory [plugins/python/pyloader.c line 109]
Traceback (most recent call last):
  File "./shareview/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ImportError: No module named django.core.wsgi
unable to load app 0 (mountpoint='127.0.0.1|') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
127.0.0.1 [pid: 5594|app: -1|req: -1/29] 127.0.0.1 () {48 vars in 813 bytes} [Sat May 12 00:48:49 2018] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
chdir(): No such file or directory [plugins/python/pyloader.c line 109]
Traceback (most recent call last):
  File "./shareview/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ImportError: No module named django.core.wsgi
unable to load app 0 (mountpoint='127.0.0.1|') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
127.0.0.1 [pid: 5593|app: -1|req: -1/30] 127.0.0.1 () {50 vars in 809 bytes} [Sat May 12 00:48:50 2018] GET /favicon.ico => generated 21 bytes in 1 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
*** Starting uWSGI 2.0.17 (64bit) on [Sat May 12 00:48:53 2018] ***
compiled with version: 6.4.0 20170724 on 11 May 2018 10:53:29
os: Linux-4.9.0-deepin13-amd64 #1 SMP PREEMPT Deepin 4.9.57-1 (2017-10-19)
nodename: chier
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/chier/Desktop/django/shareview
writing pidfile to /home/chier/Desktop/django/shareview/script/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 14928
limiting address space of processes...
your process address space limit is 536870912 bytes (512 MB)
your memory page size is 4096 bytes
detected max file descriptor number: 1024
VirtualHosting mode enabled.
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (127.0.0.1:9091).
bind(): Address already in use [core/socket.c line 769]
chdir(): No such file or directory [plugins/python/pyloader.c line 109]
Traceback (most recent call last):
  File "./shareview/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ImportError: No module named django.core.wsgi
unable to load app 0 (mountpoint='127.0.0.1|') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
127.0.0.1 [pid: 5593|app: -1|req: -1/31] 127.0.0.1 () {48 vars in 813 bytes} [Sat May 12 00:49:02 2018] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
chdir(): No such file or directory [plugins/python/pyloader.c line 109]
Traceback (most recent call last):
  File "./shareview/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ImportError: No module named django.core.wsgi
unable to load app 0 (mountpoint='127.0.0.1|') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
127.0.0.1 [pid: 5593|app: -1|req: -1/32] 127.0.0.1 () {50 vars in 809 bytes} [Sat May 12 00:49:02 2018] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
...brutally killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/chier/Desktop/django/shareview
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:9091)
running /usr/local/bin/uwsgi
[uWSGI] getting INI configuration from /home/chier/Desktop/django/shareview/uwsgi.ini
*** Starting uWSGI 2.0.17 (64bit) on [Sat May 12 02:50:00 2018] ***
compiled with version: 6.4.0 20170724 on 11 May 2018 10:53:29
os: Linux-4.9.0-deepin13-amd64 #1 SMP PREEMPT Deepin 4.9.57-1 (2017-10-19)
nodename: chier
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/chier/Desktop/django/shareview
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 14928
limiting address space of processes...
your process address space limit is 536870912 bytes (512 MB)
your memory page size is 4096 bytes
detected max file descriptor number: 1024
VirtualHosting mode enabled.
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:9091 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 2.7.13+ (default, Jul 19 2017, 18:15:03)  [GCC 6.4.0 20170704]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x555e0cba8ee0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218760 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 5592)
spawned uWSGI worker 1 (pid: 24179, cores: 1)
spawned uWSGI worker 2 (pid: 24180, cores: 1)
*** Starting uWSGI 2.0.17 (64bit) on [Sat May 12 10:24:48 2018] ***
compiled with version: 6.4.0 20170724 on 11 May 2018 10:53:29
os: Linux-4.9.0-deepin13-amd64 #1 SMP PREEMPT Deepin 4.9.57-1 (2017-10-19)
nodename: chier
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/chier/Desktop/django/shareview
writing pidfile to /home/chier/Desktop/django/shareview/script/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
your processes number limit is 14928
limiting address space of processes...
your process address space limit is 536870912 bytes (512 MB)
your memory page size is 4096 bytes
detected max file descriptor number: 1024
VirtualHosting mode enabled.
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:9091 fd 3
Python version: 2.7.13+ (default, Jul 19 2017, 18:15:03)  [GCC 6.4.0 20170704]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x5596cd110700
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218760 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 7426)
spawned uWSGI worker 1 (pid: 7427, cores: 1)
spawned uWSGI worker 2 (pid: 7428, cores: 1)
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
*** Starting uWSGI 2.0.17 (64bit) on [Sat May 12 10:26:53 2018] ***
compiled with version: 6.4.0 20170724 on 11 May 2018 10:53:29
os: Linux-4.9.0-deepin13-amd64 #1 SMP PREEMPT Deepin 4.9.57-1 (2017-10-19)
nodename: chier
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/chier/Desktop/django/shareview
detected binary path: /usr/local/bin/uwsgi
chdir() to /home/chier/Desktop/django/shareview
your processes number limit is 14928
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:3031 fd 3
Python version: 2.7.13+ (default, Jul 19 2017, 18:15:03)  [GCC 6.4.0 20170704]
Python main interpreter initialized at 0x55fa023aaa60
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 521440 bytes (509 KB) for 16 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x55fa023aaa60 pid: 8411 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 8411)
spawned uWSGI worker 1 (pid: 8445, cores: 4)
spawned uWSGI worker 2 (pid: 8446, cores: 4)
spawned uWSGI worker 3 (pid: 8447, cores: 4)
spawned uWSGI worker 4 (pid: 8448, cores: 4)
*** Stats server enabled on 127.0.0.1:9191 fd: 15 ***
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
*** Starting uWSGI 2.0.17 (64bit) on [Sat May 12 10:27:51 2018] ***
compiled with version: 6.4.0 20170724 on 11 May 2018 10:53:29
os: Linux-4.9.0-deepin13-amd64 #1 SMP PREEMPT Deepin 4.9.57-1 (2017-10-19)
nodename: chier
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/chier/Desktop/django/shareview
detected binary path: /usr/local/bin/uwsgi
chdir() to /home/chier/Desktop/django/shareview
your processes number limit is 14928
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (127.0.0.1:3031).
bind(): Address already in use [core/socket.c line 769]
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
*** Starting uWSGI 2.0.17 (64bit) on [Sat May 12 10:28:47 2018] ***
compiled with version: 6.4.0 20170724 on 11 May 2018 10:53:29
os: Linux-4.9.0-deepin13-amd64 #1 SMP PREEMPT Deepin 4.9.57-1 (2017-10-19)
nodename: chier
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/chier/Desktop/django/shareview
detected binary path: /usr/local/bin/uwsgi
chdir() to /home/chier/Desktop/django/shareview
your processes number limit is 14928
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (127.0.0.1:3031).
bind(): Address already in use [core/socket.c line 769]
*** Starting uWSGI 2.0.17 (64bit) on [Sat May 12 10:33:00 2018] ***
compiled with version: 6.4.0 20170724 on 11 May 2018 10:53:29
os: Linux-4.9.0-deepin13-amd64 #1 SMP PREEMPT Deepin 4.9.57-1 (2017-10-19)
nodename: chier
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/chier/Desktop/django/shareview
writing pidfile to /home/chier/Desktop/django/shareview/script/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /home/chier/Desktop/django/shareview
your processes number limit is 14928
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (127.0.0.1:3031).
bind(): Address already in use [core/socket.c line 769]
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
...brutally killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/chier/Desktop/django/shareview
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:3031)
running /usr/local/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.17 (64bit) on [Sat May 12 02:46:42 2018] ***
compiled with version: 6.4.0 20170724 on 11 May 2018 10:53:29
os: Linux-4.9.0-deepin13-amd64 #1 SMP PREEMPT Deepin 4.9.57-1 (2017-10-19)
nodename: chier
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/chier/Desktop/django/shareview
detected binary path: /usr/local/bin/uwsgi
chdir() to /home/chier/Desktop/django/shareview
your processes number limit is 14928
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:3031 fd 3
Python version: 2.7.13+ (default, Jul 19 2017, 18:15:03)  [GCC 6.4.0 20170704]
Python main interpreter initialized at 0x55706f10c430
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 521440 bytes (509 KB) for 16 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x55706f10c430 pid: 8411 (default app)
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 8411)
spawned uWSGI worker 1 (pid: 16215, cores: 4)
spawned uWSGI worker 2 (pid: 16216, cores: 4)
spawned uWSGI worker 3 (pid: 16217, cores: 4)
spawned uWSGI worker 4 (pid: 16218, cores: 4)
...brutally killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/chier/Desktop/django/shareview
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:3031)
running /usr/local/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.17 (64bit) on [Sat May 12 02:46:49 2018] ***
compiled with version: 6.4.0 20170724 on 11 May 2018 10:53:29
os: Linux-4.9.0-deepin13-amd64 #1 SMP PREEMPT Deepin 4.9.57-1 (2017-10-19)
nodename: chier
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/chier/Desktop/django/shareview
detected binary path: /usr/local/bin/uwsgi
chdir() to /home/chier/Desktop/django/shareview
your processes number limit is 14928
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:3031 fd 3
Python version: 2.7.13+ (default, Jul 19 2017, 18:15:03)  [GCC 6.4.0 20170704]
Python main interpreter initialized at 0x563cfb5f5430
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 521440 bytes (509 KB) for 16 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x563cfb5f5430 pid: 8411 (default app)
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 8411)
spawned uWSGI worker 1 (pid: 16276, cores: 4)
spawned uWSGI worker 2 (pid: 16277, cores: 4)
spawned uWSGI worker 3 (pid: 16280, cores: 4)
spawned uWSGI worker 4 (pid: 16282, cores: 4)
...brutally killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/chier/Desktop/django/shareview
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:3031)
running /usr/local/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.17 (64bit) on [Sat May 12 02:46:53 2018] ***
compiled with version: 6.4.0 20170724 on 11 May 2018 10:53:29
os: Linux-4.9.0-deepin13-amd64 #1 SMP PREEMPT Deepin 4.9.57-1 (2017-10-19)
nodename: chier
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/chier/Desktop/django/shareview
detected binary path: /usr/local/bin/uwsgi
chdir() to /home/chier/Desktop/django/shareview
your processes number limit is 14928
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:3031 fd 3
Python version: 2.7.13+ (default, Jul 19 2017, 18:15:03)  [GCC 6.4.0 20170704]
Python main interpreter initialized at 0x559a7a4a1430
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 521440 bytes (509 KB) for 16 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x559a7a4a1430 pid: 8411 (default app)
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 8411)
spawned uWSGI worker 1 (pid: 16322, cores: 4)
spawned uWSGI worker 2 (pid: 16323, cores: 4)
spawned uWSGI worker 3 (pid: 16324, cores: 4)
spawned uWSGI worker 4 (pid: 16325, cores: 4)
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
